### ISSUE TITLE
java.lang.String cannot be cast to java.util.Map

### ISSUE THREAD

**Issue by dozturk** [bkatwal/kafka-solr-sink-connector#2] opened 2018-11-01 15:59 UTC
I tried the sink connector in my personal computer and it works properly. Exactly the same settings I am trying in the test environment, i.e.  same version of solr, same plain json data from a kafka topic and configurations but having the following error:

[---] INFO JsonConverterConfig values:
        converter.type = value
        schemas.cache.size = 1000
        schemas.enable = false
 (org.apache.kafka.connect.json.JsonConverterConfig:279)
[---] ERROR Request to collection [mh-durmus] failed due to (0) java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map, retry? 0 (org.apache.solr.client.solrj.impl.CloudSolrClient:920)
[---] ERROR Unable to send update request to solr (com.bkatwal.kafkaproject.utils.SolrSinkService:82)
[---] ERROR WorkerSinkTask{id=SolrSink-6-0} RetriableException from SinkTask: (org.apache.kafka.connect.runtime.WorkerSinkTask:577)
org.apache.kafka.connect.errors.RetriableException: org.apache.solr.client.solrj.SolrServerException: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
        at com.bkatwal.kafkaproject.utils.SolrSinkService.insert(SolrSinkService.java:83)
        at com.bkatwal.kafkaproject.utils.SolrSinkService.insert(SolrSinkService.java:35)
        at com.bkatwal.kafkaproject.SolrSinkTask.put(SolrSinkTask.java:83)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:564)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:322)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:225)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:193)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.solr.client.solrj.SolrServerException: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
        at org.apache.solr.client.solrj.impl.CloudSolrClient.requestWithRetryOnStaleState(CloudSolrClient.java:997)
        at org.apache.solr.client.solrj.impl.CloudSolrClient.request(CloudSolrClient.java:818)
        at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:194)
        at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:173)
        at com.bkatwal.kafkaproject.utils.SolrSinkService.insert(SolrSinkService.java:80)
        ... 13 more
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
        at org.apache.solr.common.cloud.DocRouter.getRouteField(DocRouter.java:53)
        at org.apache.solr.common.cloud.CompositeIdRouter.sliceHash(CompositeIdRouter.java:46)
        at org.apache.solr.common.cloud.HashBasedRouter.getTargetSlice(HashBasedRouter.java:38)
        at org.apache.solr.client.solrj.request.UpdateRequest.getRoutes(UpdateRequest.java:262)
        at org.apache.solr.client.solrj.impl.CloudSolrClient.directUpdate(CloudSolrClient.java:503)
        at org.apache.solr.client.solrj.impl.CloudSolrClient.sendRequest(CloudSolrClient.java:1014)
        at org.apache.solr.client.solrj.impl.CloudSolrClient.requestWithRetryOnStaleState(CloudSolrClient.java:885)
        ... 17 more

I would really appreciate if you can direct me for this issue?

**Comment by bkatwal** [comment] 2019-01-01 11:05
Hi @dozturk, you still facing this issue?
Solr is throwing exception in your issue:

Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
at org.apache.solr.common.cloud.DocRouter.getRouteField(DocRouter.java:53)
at org.apache.solr.common.cloud.CompositeIdRouter.sliceHash(CompositeIdRouter.java:46)
at org.apache.solr.common.cloud.HashBasedRouter.getTargetSlice(HashBasedRouter.java:38)
at org.apache.solr.client.solrj.request.UpdateRequest.getRoutes(UpdateRequest.java:262)
at org.apache.solr.client.solrj.impl.CloudSolrClient.directUpdate(CloudSolrClient.java:503)
at org.apache.solr.client.solrj.impl.CloudSolrClient.sendRequest(CloudSolrClient.java:1014)
at org.apache.solr.client.solrj.impl.CloudSolrClient.requestWithRetryOnStaleState(CloudSolrClient.java:88

Could you please confirm the solr version you are using here? and confirm if you are running solr in cloud mode in both local and in your test environment?

**Comment by bkatwal** [comment] 2019-01-07 10:08
closing this issue.

**Closed as completed by bkatwal** 2019-01-07 10:08 UTC
